### ISSUE TITLE
Delete BDD test stalls the integration tests

### ISSUE THREAD

**Issue by KranthiGV** [CSCI-GA-2820-SP23-003/products#110]
**Describe the bug**
Delete BDD test is failing on the integration test suite. This is stalling the deployment.

**Observed behavior**
The test runs successfully locally.

**Comment by KranthiGV** [comment]
Let us disable the test till we figure out what's the root cause.

**Comment by ruoyuGao** [comment]
Currently, we use see "retrieved failed" to replace not see "Success", it will timeout on our endpoint but success at our local dev env. So we will disable it first and search root problem in the future.
