### ISSUE TITLE
Create action for automated testing of PRs

### ISSUE THREAD

**Issue by KranthiGV** [CSCI-GA-2820-SP23-003/products#17]
**As a** developer
**I need** automated testing of PRs
**So that** we can ensure high quality code check-ins and prevent product regressions
   
 ### Details and Assumptions
* We need to follow test driven development practices.
* We should have ability to add new tests.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given developer works on a feature/bug
 When developer creates a PR
 Then automated suite of tests are run
```

**Comment by Hanhlin** [comment]
Duplicate of #47
