### ISSUE TITLE
Add GitHub Actions CI Badge to README.md

### ISSUE THREAD

**Issue by Hanhlin** [CSCI-GA-2820-SP23-003/products#36]
**As a** Developer
**I need** to show a GitHub Actions CI Badge on the README.md file 
**So that** others know if the current build is passing or broken  
   
 ### Details and Assumptions
 *  Use GitHub actions to test the build
 *  Should add a Code Coverage badge to the README.md
 *  Should add the CI build badge to the README.md.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the repository exists
 When someone looks at the README.md file on the master branch
 Then they should be able to see the CI build badge and CodeCov badge
```

**Comment by ruoyuGao** [comment]
I will add all the story for requirement 2 later, and take all of them
