### ISSUE TITLE
Add a /health endpoint to the Product service for Kubernetes health check

### ISSUE THREAD

**Issue by Hanhlin** [CSCI-GA-2820-SP23-003/products#38]
**As a** Developer/ System Administrator
**I need** a health check endpoint for Kubernetes
**So that** I can know the service is running and good for deployment
   
 ### Details and Assumptions
 * Add a `/health` endpoint to the Product service and should return `{"status":"OK}, 200`
  
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is running
 When sending a GET request to /health
 Then the service should return {"status": "OK"}
```

**Comment by KranthiGV** [comment]
Raised PR #51
