### ISSUE TITLE
Invite the team to IBM Cloud account

### ISSUE THREAD

**Issue by Hanhlin** [CSCI-GA-2820-SP23-003/products#39]
**As a** GitHub Repo Maintainer
**I need** invite all members of the team to IBM Cloud  
**So that** everyone can deploy to the Kubernetes cluster
   
 ### Details and Assumptions
 * Each member of the team will need to create their own IBM Accounts
 * Team member who has GitHub Repo Maintainer access should also be the one who shares the cloud account
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given everyone has an IBM account and is invited to share a cluster
 When someone tries to deploy to the cluster
 Then the deployment should work
```

**Comment by wonkwonlee** [comment]
Every member is now invited via NYU school email
