### ISSUE TITLE
Add help function to perform some stateful Action on the Resource

### ISSUE THREAD

**Issue by ruoyuGao** [CSCI-GA-2820-SP23-003/products#40]
**As a Developer/ System Administrator
**I need to perform some stateful Action on the Resource
**So that we can make sure our query result is correct
   
 ### Details and Assumptions
 * Add help function to perform LIKE actions on resources
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is running
 When we use the help function to perform state action on resources
 Then query result should be correct
```

**Comment by Hanhlin** [comment]
@ruoyuGao Should we perform functions other than CRUD, such as liking a product?

**Comment by wonkwonlee** [comment]
Yeah I think liking is easy-to-implement, and a good review for our products case.
