### ISSUE TITLE
Make an IBM Cloud account for develop

### ISSUE THREAD

**Issue by ruoyuGao** [CSCI-GA-2820-SP23-003/products#41]
As a Developer/ System Administrator
I need  to make an IBM Cloud account
So that I can deploy our service on the cloud in the future
   
 ### Details and Assumptions
 * Create an IBM account
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is running
 When we want to deploy it to the cloud
 Then we need to have an IBM cloud account first
```

**Comment by Hanhlin** [comment]
Everyone on the team has created an IBM account.
