### ISSUE TITLE
Create a dev namespace in the Kubernetes cluster

### ISSUE THREAD

**Issue by Hanhlin** [CSCI-GA-2820-SP23-003/products#54]
**As a** Developer
**I need** to add a dev namespace in the Kubernetes cluster
**So that** I can deploy the development versions of the Product Service  
   
 ### Details and Assumptions
 * The Kubernetes cluster is running 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the cluster is running
 When adding a dev namespace to the Kubernetes cluster 
 Then the service can be deployed in a dev environment
```

**Comment by KranthiGV** [comment]
![image.png](https://images.zenhubusercontent.com/63e5361097d5a7358d5c16d0/4043e2d3-1663-45fd-b2fe-2b7dfebdb0de)
