### ISSUE TITLE
Create a prod namespace in the Kubernetes cluster

### ISSUE THREAD

**Issue by Hanhlin** [CSCI-GA-2820-SP23-003/products#55]
**As a** Developer
**I need** to add a prod namespace in the Kubernetes cluster
**So that** I can deploy the production versions of the Product Service
   
 ### Details and Assumptions
 * The Kubernetes cluster is running
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the cluster is running
 When adding a prod namespace to the Kubernetes cluster 
 Then the service can be deployed in a prod environment
```

**Comment by KranthiGV** [comment]
![image.png](https://images.zenhubusercontent.com/63e5361097d5a7358d5c16d0/b01ce0ef-8b4d-488f-836a-72396101354f)
