### ISSUE TITLE
Install IBM Cloud CLI in devcontainer

### ISSUE THREAD

**Issue by KranthiGV** [CSCI-GA-2820-SP23-003/products#69]
**As a** Software Developer
**I need** to update my devcontainer environment to download and install the IBM Cloud CLI
**So that** I can interact with IBM Cloud services and manage my Kubernetes cluster

### Details and Assumptions
* A devcontainer environment is set up

### Acceptance Criteria

```gherkin
Given a devcontainer environment
When I update the configuration to download and install the IBM Cloud CLI
Then the IBM Cloud CLI is successfully installed
I can use it to manage Kubernetes cluster from within the devcontainer
```

**Comment by Hanhlin** [comment]
[Message Link](https://nyu-devops-spring23-3.slack.com/archives/C04LNRX03JL/p1680550955986319): The prof has already included this in the starter code for the repo. So there is nothing to do.
