### ISSUE TITLE
Connect the DevOps pipeline to the GitHub repository via a webhook

### ISSUE THREAD

**Issue by Hanhlin** [CSCI-GA-2820-SP23-003/products#79]
**As a** Developer
**I need** to connect the DevOps pipeline to the GitHub repository via a webhook
**So that** the DevOps CI/CD Pipeline is connected
   
 ### Details and Assumptions
 * The owner of the repo must do this.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is up and running
 When connecting the DevOps pipeline to the GitHub repository via a webhook
 Then the DevOps CI/CD Pipeline is connected to the project
```

**Comment by wonkwonlee** [comment]
![image](https://user-images.githubusercontent.com/28593767/234180961-2e0b63c7-482c-4fb9-9481-e3bdcf2345ce.png)

Connected the Products DevOps pipeline to the GitHub repository
