### ISSUE TITLE
Add a Build Stage to the DevOps Pipeline

### ISSUE THREAD

**Issue by Hanhlin** [CSCI-GA-2820-SP23-003/products#80]
**As a** Developer
**I need** to add a Build stage to the DevOps Pipeline
**So that** the Build stage will do the work to ensure the code is safe and good to deploy
   
 ### Details and Assumptions
 *Should add a job to checkout the code from GitHub
 *Should add a job to run TDD tests with `nosetests`
 *Should add a job to build a Docker image and push it to the IBM Cloud Container Registry
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a Build stage is added in the DevOps Pipeline
 When Build stage is triggered
 Then it should automatically run the above 3 jobs
```

**Comment by wonkwonlee** [comment]
![image](https://user-images.githubusercontent.com/28593767/234183781-8fc108b5-ab5f-43a6-8df0-30a628308031.png)

Added a Build Stage to the DevOps Pipeline
- Added a job to checkout the code from GitHub
- Added a job to run TDD tests with nosetests
- Added a job to build a Docker image and push it to the IBM Cloud Container Registry

**Comment by wonkwonlee** [comment]
Need to add updated Project API Key

**Comment by wonkwonlee** [comment]
Updated project API key is added
