### ISSUE TITLE
Add Integration Test Stage with behave to DevOps Pipeline

### ISSUE THREAD

**Issue by KranthiGV** [CSCI-GA-2820-SP23-003/products#87]
**As a** developer
**I need** an Integration Test Stage in the pipeline to run integration tests using behave against the Dev deployment  
**So that** I can ensure the application is functioning correctly before promoting to the Production environment

### Details and Assumptions
* The pipeline should already have multiple stages
* Add an Integration Test Stage to run BDD tests with behave against the Dev deployment
* Ensure the tests target the Development instance

### Acceptance Criteria

```gherkin
Given the DevOps Pipeline is running
When the Integration Test Stage is reached
Then it should run integration tests using behave against the Dev deployment
And only proceed to the Production stage if all tests pass

**Comment by ruoyuGao** [comment]
it seems we need to do test for every stage instead of create a new stage for that
