### ISSUE TITLE
Create a database model for Products resource

### ISSUE THREAD

**Issue by wonkwonlee** [CSCI-GA-2820-SP23-003/products#9]
**As a** Developer
**I need** to design a database model for the Products resource
**So that** I can perform CRUD and List operations on the Products resource
   
 ### Details and Assumptions
 * Product items and their details will be stored in the PostgreSQL database
 * Each item has a unique id, a name, description, price, and other attributes
 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the service is running
 When a CRUD or List operation is performed on Products resource
 Then related information is retrieved from or stored in the database
```

**Comment by Hanhlin** [comment]
I am sharing my preliminary idea for the database model and would appreciate any suggestions or modifications you may have.
![products_model](https://user-images.githubusercontent.com/66856788/221048244-3ac44b4c-eb5f-434f-af85-04d6a73607b6.png)
